export const prompts : string[] = [
    "A whimsical forest with animals made entirely of candy",
    "An underwater city inhabited by mermaids and seahorses in a futuristic setting.",
    "A cityscape where buildings are replaced with giant mushrooms and flowers",
    "A surreal landscape where clouds are made of cotton candy and the trees are upside down",
    "A steampunk-inspired world with flying ships and mechanical animals",
    "A garden where flowers bloom in the shape of musical instruments",
    "A desert scene with cacti that have branches made of glowing neon lights",
    "A futuristic laboratory with scientists conducting experiments on floating islands",
    "A futuristic sports stadium where athletes compete on hoverboards",
    "An enchanted library filled with books that come to life as you read them",
    "A cityscape where buildings are made of intricate origami",
    "A mythical creature that combines the features of a dragon, a peacock and a jellyfish",
    "A floating island covered in lush greenery and waterfalls, suspended in the sky",
    "A futuristic space station with crystalline structures and floating gardens",
    "An underwater garden with bioluminescent plants and colorful coral reefs",
    "A bustling marketplace in a fantasy realm, filled with exotic creatures and magical artifacts",
    "A surreal tea party with floating teacups and cakes that change flavors with each bite",
    "A serene meditation garden with statues made of flowing water",
    "A futuristic cityscape where transportation is done through transparent tubes",
    "A whimsical carousel with mythical creatures instead of horses, such as unicorns and griffins",
    "A vibrant underwater world where fish have wings and fly through the ocean",
    "A magical forest with trees that have glowing crystals instead of leaves",
    "A futuristic cityscape with buildings that twist and curve like ribbons",
    "A surreal beach with sand made of colorful gemstones and seashells that sparkle",
    "An ancient temple hidden deep in the jungle, guarded by stone statues that come to life",
    "A steampunk-inpired train traveling through a landscape of gears and clockwork mechanisms",
    "A mystical garden where plants grow in the shape of mythical creatures",
    "A cosmic dance of planets and stars forming intricate patterns in the night sky",
    "A futuristic floating city with transparent domes and gardens suspended in mid-air",
    "A surreal art gallery with paintings that come to life and interact with the viewers",
    "A floating island inhabited by miniature elephants and flying squirrels.",
    "A candy-powered rocket ship blasting off into a galaxy made of rainbow swirls.",
    "A secret garden where flowers bloom into delicate porcelain sculptures.",
    "A whimsical village populated by talking animals in top hats and bowties.",
    "A futuristic cityscape where holographic art installations come to life.",
    "A magical potion lab with bubbling cauldrons and shelves filled with enchanted ingredients.",
    "An underwater realm with seashell palaces and friendly mermaid musicians.",
    "A mythical forest where trees whisper secrets and glow with bioluminescent patterns.",
    "A steampunk-inspired train station with a clockwork conductor and passengers in Victorian attire.",
    "A mystical portal that transports you to a land of floating islands and levitating waterfalls.",
    "An alien marketplace with peculiar creatures selling exotic fruits and sparkling gemstones.",
    "A towering treehouse nestled in the branches of a colossal ancient tree.",
    "A celestial observatory where astronomers study constellations that form vibrant works of art.",
    "A hidden library with books that contain living stories that interact with readers.",
    "A robot factory where mechanical beings assemble themselves with intricate precision."
];