import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Search from '@/components/Search';

export default function Home() {
  return (
    <>
      <Head>
        <title>ImageGENIE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main className='w-full h-screen bg-tertiary text-lightest overflow-x-hidden overflow-y-scroll scrollbar-thin scrollbar-track-primary/20 scrollbar-thumb-secondary font-bodyFont'>
        <Navbar/>
        <div className='w-full h-[90vh]'>
          <Search/>
        </div>
      </main>
    </>
  )
}
